// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://https://jpselvijuuovdgxohemg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwc2VsdmlqdXVvdmRneG9oZW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzU0OTEsImV4cCI6MjA2NTI1MTQ5MX0.D3STn355EozC6VAtJ0HONSC-NSzJ8IGwh4NwEPAATi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);