// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaamssbtvatjnpgwikur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhYW1zc2J0dmF0am5wZ3dpa3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzE1NTAsImV4cCI6MjA2NDMwNzU1MH0.Gf2Ohn4Cn5gv4T1pcTm7PSmKEiJqTHsQIge3g6DPNaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);